import { config } from "dotenv";
config();

const ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET";
const REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET";
const ACCESS_TOKEN_EXPIRY = "1h";
const REFRESH_TOKEN_EXPIRY = "1d";

const SECRETS = {
  MONGO_CONNECTION_STRING: process.env.MONGO_CONNECTION_STRING,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
};

export {SECRETS, ACCESS_TOKEN_SECRET, ACCESS_TOKEN_EXPIRY, REFRESH_TOKEN_EXPIRY, REFRESH_TOKEN_SECRET};
