import { config } from "dotenv";
config();

const ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET";
const REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET";
const ACCESS_TOKEN_EXPIRY = "1h";
const REFRESH_TOKEN_EXPIRY = "1d";

const SECRETS = {
  MONGO_CONNECTION_STRING: process.env.MONGO_CONNECTION_STRING,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  INFURA_IPFS_PROJECT_ID: process.env.INFURA_IPFS_PROJECT_ID,
  INFURA_IPFS_API_KEY_SECRET: process.env.INFURA_IPFS_API_KEY_SECRET,
  INFURA_API_ENDPOINT: process.env.INFURA_API_ENDPOINT,
  INFURA_API_PORT: process.env.INFURA_API_PORT
};

export {SECRETS, ACCESS_TOKEN_SECRET, ACCESS_TOKEN_EXPIRY, REFRESH_TOKEN_EXPIRY, REFRESH_TOKEN_SECRET};
